Jenkinsfile
cypress.config.js
cypress/e2e/home/home-page.spec.cy.ts
cypress/fixtures/queries/default-query-response.json
cypress/steps/yasgui-steps.ts
ontotext-yasgui-web-component/package-lock.json
ontotext-yasgui-web-component/package.json
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui/ontotext-yasgui.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui/readme.md
ontotext-yasgui-web-component/src/docs/development-guide.md
ontotext-yasgui-web-component/src/js/main.js
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/configurator.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configurator.ts
ontotext-yasgui-web-component/src/services/yasgui/yasgui-builder.ts
package-lock.json

What?
Added a configurator for base yasgui configuration.
Why?
As clients of component we need an opportunity to configure endpoints and headers of yasgui component.
How?
Implements base building flow of a yasgui instance.
Implements builder of yasgui configuration.
Implements a configuration which will configure base configuration of yasgu.

GDB-7681: Initial implementation of component

---

Jenkinsfile
cypress.config.js
cypress/e2e/view-configurations.spec.cy.ts
cypress/steps/page-steps.ts
cypress/steps/yasgui-steps.ts
cypress/steps/yasqe-steps.ts
cypress/steps/yasr-steps.ts
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/pages/view-configurations/index.html
ontotext-yasgui-web-component/src/pages/view-configurations/main.js
ontotext-yasgui-web-component/src/pages/view-modes/main.js
ontotext-yasgui-web-component/src/services/yasgui/configuration/configurator.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configurator.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasqe-configurator.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasr-configurator.ts
ontotext-yasgui-web-component/src/services/yasgui/yasgui-builder.ts
package-lock.json
package.json

Added support for additional yasgui configurations:
* query - default query when a tab is opened;
* initialQuery - initial query when yasgui is rendered if not set the default query will be set;
* showEditorTabs - if the yasgui tabs should be rendered or not. If true or undefined editors tabs will be shown;
* showResultTabs - if the result tabs should be rendered or not. If true or undefined result tabs will be shown. Added firing of "queryExecuted" event when a query is executed.
Clients of component using different representation of yasgui and that's what the configurations are needed for.
* Extends yasgui configuration with additional options;

GDB-7681: Initial ontotext-yasgui component implementation.

---

JenkinsfileRelease

There were a problem with "ch ontotext-yasgui-web-component" command

Move version scripts into a file

---

ontotext-yasgui-web-component/README.md

What?
Updates component setup for angular application.
Why?
There was a missed step of component setup.
How?
Added explanation of missed step.

Updates the readme file.

---

ontotext-yasgui-web-component/docs/developers-guide.md
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/components/save-query-dialog/readme.md
ontotext-yasgui-web-component/src/components/save-query-dialog/save-query-dialog.tsx
ontotext-yasgui-web-component/src/index.html
ontotext-yasgui-web-component/src/js/main.js
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/services/event-service.ts
ontotext-yasgui-web-component/src/services/service-factory.ts
ontotext-yasgui-web-component/src/services/translation.service.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
ontotext-yasgui-web-component/src/services/yasgui/ontotext-yasgui-service.ts
ontotext-yasgui-web-component/src/services/yasgui/yasgui-builder.ts
ontotext-yasgui-web-component/src/services/yasqe/yasqe-service.ts

What?
Implements a service for dependency injection.
Why?
As developers, we needs uniform way to create services and inject them into another service.
How?
Implement a service which have to be used when an instance of another service is needed. It takes care of service creation and a service to have only one instance.

Implements service factory

---

cypress/e2e/editor-actions/edit-saved-query.spec.cy.ts
cypress/e2e/editor-actions/save-query.spec.cy.ts
cypress/steps/yasqe-steps.ts
cypress/support/e2e.js
cypress/tsconfig.json
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/components/save-query-dialog/readme.md
ontotext-yasgui-web-component/src/components/save-query-dialog/save-query-dialog.tsx
ontotext-yasgui-web-component/src/components/saved-queries-popup/readme.md
ontotext-yasgui-web-component/src/components/saved-queries-popup/saved-queries-popup.scss
ontotext-yasgui-web-component/src/components/saved-queries-popup/saved-queries-popup.tsx
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/model.ts
ontotext-yasgui-web-component/src/pages/actions/main.js
package-lock.json
package.json

This MR introduces support for editing of saved queries.
GDB workbench supports functionality for saving sparql queries as well as managing the saved queries like editing them.
* Introduced the edit query action in the saved queries popup as well as respective handlers in the ontotext yasgui component.
* Extended models and improved the save query handling.

GDB-7820 introduce saved query edit operation

---

cypress/e2e/languages.spec.cy.ts
cypress/steps/yasr-steps.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx

What?
Sometimes there is an NPE when language is changed.
Why?
Changing of language is asynchronous process and sometimes changing of language happen before the yasqui is initialized.
How?
Added a wait function which wait component to be ready.

Fixes NPE when language is changed

---

Yasgui/packages/yasqe/src/index.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/models/event.ts
yasgui-patches/2023-02-13_1_run_query_button_label_and_icon.patch

GDB-7890 style query button and improve query event
Style the query button and add query mode to queryExecuted event.
Style of the button should match the one in the workbench. Also the query mode is needed in order the client to be able to change the request as needed.
* Styled the button.
* Added the query mode to the query executed event.

GDB-7890 query button and event improvements

---

Yasgui/packages/yasgui/src/Tab.ts
Yasgui/packages/yasqe/src/index.ts
Yasgui/packages/yasqe/src/sparql.ts
Yasgui/packages/yasr/src/extended-yasr.ts
Yasgui/packages/yasr/src/plugins/extended-table/extended-table.ts
cypress/e2e/keyboard-shortcuts.spec.cy.ts
cypress/fixtures/queries/explain-plan-query-response.json
cypress/steps/keyboard-shortcut-steps.ts
cypress/stubs/query-stubs.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/models/internal-events/internal-notification-message-event.ts
ontotext-yasgui-web-component/src/services/keyboard-shortcut-service.ts
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts
yasgui-patches/2023-03-18-extends_YASGUI_with_explain_functionality_.patch

Implement "Explain plan query" action.
The WB have got implementation of this action.

GDB-8023: implement "Explain plan query" shortcut action.

---

Yasgui/packages/yasr/src/index.ts
Yasgui/packages/yasr/src/plugins/response/extended-response.ts
Yasgui/packages/yasr/src/plugins/response/index.ts
cypress/e2e/defalt-view.spec.cy.ts
cypress/e2e/editor-actions/execute-query.spec.cy.ts
cypress/e2e/keyboard-shortcuts.spec.cy.ts
cypress/e2e/languages.spec.cy.ts
cypress/e2e/yasgui-tabs.spec.cy.ts
cypress/e2e/yasr/download-as.spec.cy.ts
cypress/e2e/yasr/pagination.spec.cy.ts
cypress/e2e/yasr/plugin-raw-response.spec.cy.ts
cypress/e2e/yasr/plugin-table.spec.cy.ts
cypress/fixtures/raw-response/expected-raw-response.json
cypress/steps/yasgui-steps.ts
cypress/steps/yasqe-steps.ts
cypress/steps/yasr-steps.ts
yasgui-patches/2023-03-30_GDB-7712_extend_raw_response_and_remove_the_download_response_button.patch

Raw response plugin has a download action button which duplicates our download menu so we removed it.
We don't need to duplicate the download option.
* Extended the raw response plugin.
* Removed the button from the raw response plugin.

GDB-7712 updated raw response plugin for yasr

---

ontotext-yasgui-web-component/src/components/copy-resource-link-button/copy-resource-link-button.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/models/event.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-create-saved-query-event.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-download-as-event.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-dropdown-value-selected-event.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-event-types.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-event.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-notification-message-event.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-share-query-event.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-show-resource-copy-link-dialog-event.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-show-saved-queries-event.ts
ontotext-yasgui-web-component/src/models/output-events/count-query-event.ts
ontotext-yasgui-web-component/src/models/output-events/count-query-response-event.ts
ontotext-yasgui-web-component/src/models/output-events/output-event-types.ts
ontotext-yasgui-web-component/src/models/output-events/query-event.ts
ontotext-yasgui-web-component/src/services/event-service.ts
ontotext-yasgui-web-component/src/services/notification-message-service.ts
ontotext-yasgui-web-component/src/services/yasqe/yasqe-service.ts

Refactoring the event service functionality. Added types to output and input events.

Refactoring the event service functionality

---

Yasgui/packages/utils/src/index.ts
Yasgui/packages/yasgui/src/Tab.ts
Yasgui/packages/yasgui/src/defaults.ts
Yasgui/packages/yasgui/src/index.ts
Yasgui/packages/yasqe/src/defaults.ts
Yasgui/packages/yasqe/src/index.ts
Yasgui/packages/yasqe/src/sparql.ts
Yasgui/packages/yasr/src/index.ts
Yasgui/packages/yasr/src/plugins/error/extended-error.ts
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/models/event.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-count-query-event.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-count-query-response-event.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-event-types.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-query-event.ts
ontotext-yasgui-web-component/src/models/internal-events/internal-query-executed.ts
ontotext-yasgui-web-component/src/models/output-events/count-query-event.ts
ontotext-yasgui-web-component/src/models/output-events/count-query-response-event.ts
ontotext-yasgui-web-component/src/models/output-events/output-event-types.ts
ontotext-yasgui-web-component/src/models/output-events/query-event.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/services/event-service.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
yasgui-patches/2023-04-13-refactoring_output_events.patch

Refactoring events fired by yasgui to "ontotext-yasgui-web-component" output event emitter.
Simplify emitting of events from yasgui to "ontotext-yasgui-web-component" clients.
Pass event service to yasgui components through configuration

Refactoring output events

---

Yasgui/packages/yasr/src/plugins/table/index.ts
yasgui-patches/2023-11-13-GDB-9006_make_yasr_ellipse_checkbox_unchecked_by_default.patch

Make yasr ellipse checkbox unchecked by default.
By requirement.
Make it unchecked initially

GDB-9006 uncheck ellipse checkbox by default

---

cypress/e2e/yasr/pagination.spec.cy.ts
ontotext-yasgui-web-component/src/components/pagination/pagination.tsx
ontotext-yasgui-web-component/src/index.html
ontotext-yasgui-web-component/src/pages/pagination/index.html

Change pagination behavior to show always 5 pages if total pages are at least 5.
This is the expected behavior for the workbench
Extended and fixed the login in pagination and also fixed and extended the tests.

GDB-9000 change pagination behavior

---

cypress/e2e/autocomplete/sesame-autocomplete.spec.cy.ts
cypress/e2e/editor-actions/execute-query.spec.cy.ts
cypress/e2e/editor-actions/save-query.spec.cy.ts
cypress/e2e/editor-actions/share-query.spec.cy.ts
cypress/e2e/yasr/download-as.spec.cy.ts
cypress/stubs/constants.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/services/translation.service.ts

Fix default query formatting in yasqe.
The query had a bad formatting defined in the configuration. This needs to be fixed in order to comply with the current workbench.
* Fixed the query formatting in the yasgui configuration.
Additionally added some minor refactorings in the translation.service.ts

GDB-8990 fix default query formatting in yasqe

---

ontotext-yasgui-web-component/src/components/keyboard-shortcuts-dialog/keyboard-shortcuts-dialog.scss

Increased the width of the hotkeys dialog.
It looks better when hotkeys descriptions are listed on single line.
Increase the width of the dialog

GDB-9002 improve styling of the hotkeys dialog

---

ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json

Change charts plugin label.
For consistency with current workbench.
Changed the label in bundles.

GDB-9443 change charts plugin label

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss

Fix literal position in rdf star triple.
Seems like the literal in rdf star triples is no properly styled and appears a bit off compared to uris on subject or object position.
Added appropriate style.

GDB-9578 fix literal position in rdf star triple

---

ontotext-yasgui-web-component/src/plugins/yasr/charts/charts-plugin.ts
ontotext-yasgui-web-component/src/plugins/yasr/pivot-table/pivot-table-plugin.ts

What
Added translations for the Google Chart Editor.
Why
The Google Chart Editor had not been translated.
How
Added the current language to the Google Chart loader configuration.

Added translation for Google Chart Editor

---

ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json

Reverts Ontotext-AD/ontotext-yasgui#281

Revert "GDB-10933 - add more descriptive label to "Download as" button"
