cypress/e2e/view-modes.spec.cy.ts
cypress/steps/page-steps.ts
cypress/steps/yasgui-steps.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/docs/development-guide.md
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/pages/view-modes/index.html
ontotext-yasgui-web-component/src/pages/view-modes/main.js
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configurator.ts

Support for the yasgui layout orientation switching is added. The orientation of the yasgui can be switched by setting config.orienation='orientation-horizontal' or 'orientation-vertical' where the vertical orientation is the default.
The client expectation is to be able to switch the orientation if different views.
* Extend the yasgui configuration with additional options for the orientation modes.
* Expose the configuration mode as a css class on the host element and style the yasgui appropriately.
* Add tests.

GDB-7704 Introduce yasgui layout orientation switching

---

ontotext-yasgui-web-component/package-lock.json
ontotext-yasgui-web-component/package.json
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
package-lock.json

What?
There is a problem with translation in single page application. When user is loads a view with ontotext-yasgui-web-component and changes the language or refresh such view everything is ok, but if he/she goes to other view, changes tha language and returns back to the view with the component then all labels of ontotext-yasgui-web-component are translated on previous language only labels of original yasgui are translated correctly to new one.
Why?
The setup of the language was in init method of ontotext-yasgui-web-component component. It was hooked on "componentDidLoad" of component's Lifecycle phase.This phase is executed when the component is loaded that's why all labels of "ontotext-yasgui-web-component" are already translated on previous language. In the init method we set the new …

Fixes setup of translation service

---

cypress/e2e/persistence.spec.cy.ts
cypress/steps/persistence-steps.ts
ontotext-yasgui-web-component/README.md
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/pages/persistence/instance/index.html
ontotext-yasgui-web-component/src/pages/persistence/instance/main.js
ontotext-yasgui-web-component/src/pages/persistence/second-instance/index.html
ontotext-yasgui-web-component/src/pages/persistence/second-instance/main.js
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts

Extends ontotext-yasgui-web-component to support persistence context
What?
Added persistence context to "ontotext-yasgui-web-component".
Why?
Client needs to have independent instances of "ontotext-yasgui-web-component". This means that you when make changes to an instance, all other will not be affected.
How?
Yasgui has such functionality. Extends "ontotext-yasgui-web-component" with configuration "componentId". The value of configuration will be used to create independent persisted state of component.

GDB-7815: Extends ontotext-yasgui-web-component to support persistence context

---

cypress/e2e/editor-actions/configure-actions.spec.cy.ts
cypress/e2e/editor-actions/show-saved-queries.spec.cy.ts
cypress/steps/actions-page-steps.ts
cypress/steps/yasgui-steps.ts
cypress/steps/yasqe-steps.ts
ontotext-yasgui-web-component/docs/developers-guide.md
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/components/saved-queries-popup/readme.md
ontotext-yasgui-web-component/src/components/saved-queries-popup/saved-queries-popup.scss
ontotext-yasgui-web-component/src/components/saved-queries-popup/saved-queries-popup.tsx
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/models/event.ts
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/model.ts
ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/pages/actions/index.html
ontotext-yasgui-web-component/src/pages/actions/main.js
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
ontotext-yasgui-web-component/src/services/yasqe/yasqe-service.ts

Introduce a show saved queries action.
Save query action exists in current implementation in the GDB WB. It allows the user to load and see the available saved queries then for each query additional actions can be performed, e.g. select, edit, delete.
* Add custom button in the yasqe buttons extension point. The button rises an event for loading of the saved queries. Handling of this event is responsibility of the client who then must set the queries list in the config. Setting the queries in the config triggers the popup to appear.
* Add a saved queries popup which implements the visualization of the saved queries list. Each saved query is represented as a link and can be selected via click which then opens the query in a new yasgui tab. The dialog can be closed via click outside.
* …

GDB-7784 implement show saved queries action

---

JenkinsfileRelease

Removed the release notes building script from the jenkins file
It seems like there is a change in the github API and the script currently doesn't work as expected and throws error.
Removed the script from the jenkins file. It can be introduced again someday but it'd require some extra work to be updated.

Remove release notes script from jenkins file.

---

cypress/e2e/editor-actions/configure-actions.spec.cy.ts
cypress/e2e/editor-actions/save-query.spec.cy.ts
cypress/e2e/editor-actions/show-saved-queries.spec.cy.ts
cypress/steps/yasgui-steps.ts
cypress/steps/yasqe-steps.ts
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/confirmation-dialog/readme.md
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/components/saved-queries-popup/readme.md
ontotext-yasgui-web-component/src/components/saved-queries-popup/saved-queries-popup.tsx
ontotext-yasgui-web-component/src/models/event.ts
ontotext-yasgui-web-component/src/models/model.ts
ontotext-yasgui-web-component/src/services/event-service.ts
ontotext-yasgui-web-component/src/services/yasgui/ontotext-yasgui-service.ts
ontotext-yasgui-web-component/src/services/yasqe/yasqe-service.ts

When creating new yasgui tab the actions in the previous tab disappears.
The reason is that we build the button instances once and reuse them for each new tab. The yasqe reattaches the buttons to each new instance making them to disappear from the other once.
* Make button builders to produce new button instance on each invocation.
* Also calculate the saved queries popup position based on the actual button which triggered it.

GDB-7821 fixes disappearing yasqe actions when switching tabs

---

cypress/e2e/saved-query/share-saved-query.cpec.cy.ts
cypress/steps/actions-page-steps.ts
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/components/save-query-dialog/save-query-dialog.tsx
ontotext-yasgui-web-component/src/components/saved-queries-popup/saved-queries-popup.tsx
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts
ontotext-yasgui-web-component/src/models/saved-query-configuration.ts
ontotext-yasgui-web-component/src/pages/actions/index.html
ontotext-yasgui-web-component/src/pages/actions/main.js

Allow the client to open a query model in a new or existing tab depending on if there is already existing tab with the same name and query.
The client would needs to open a shared query in editor tab, be it a new or existing one.
* Exposed a component instance method for opening a query in a tab in the editor.
* Renamed the saved query config file to be closer to its purpose.

GDB-7785 Introduce ability to open shared query via method

---

cypress/e2e/editor-actions/configure-actions.spec.cy.ts
cypress/e2e/editor-actions/expand-results-over-sameas.spec.cy.ts
cypress/e2e/editor-actions/include-inferred-statements.spec.cy.ts
cypress/steps/actions-page-steps.ts
cypress/steps/yasqe-steps.ts
ontotext-yasgui-web-component/docs/developers-guide.md
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/models/event.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/pages/actions/index.html
ontotext-yasgui-web-component/src/pages/actions/main.js
ontotext-yasgui-web-component/src/services/yasqe/yasqe-service.ts

This MR introduces support for action that toggles the expand results over owl:sameAs.
GDB workbench supports changing the results expansion over owl:sameAs.
* Introduced the new action button in the yasqe which allows the sameAs configuration and request parameter and to be toggled.

GDB-7786 introduce expand results over owl:sameAs action

---

ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts

Fixes NPE when type of cell is not uri.
What?
There is an error when sorting results in table plugin.
Why?
Implementation is not completed. At the moment it is ready for type uri only. When the content of cell is not uri an empty string is returned and sort functionality throws an exception because can't found first element into the cell.
How?
Changed return type to be empty div element instead empty string.

Fixes NPE when type of cell is not uri.

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts

What?
From time to time there is an NPE when instantiating ontotext-yasgui-web-component.
Why?
The initializer function is called before the ontotext yasgui DOM is created.
How?
Execution of function is prevented if DOM is not created.

Fixes NPE when ontotext yasgui

---

README.md
cypress/e2e/defalt-view.spec.cy.ts
cypress/e2e/yasgui-toolbar.spec.cy.ts
cypress/e2e/yasr/plugin-table.spec.cy.ts
cypress/steps/default-view-page-steps.ts
cypress/steps/page-steps.ts
ontotext-yasgui-web-component/README.md
ontotext-yasgui-web-component/docs/developers-guide.md
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/js/main.js
ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts
ontotext-yasgui-web-component/src/pages/default-view/index.html
ontotext-yasgui-web-component/src/pages/default-view/main.js
ontotext-yasgui-web-component/src/pages/multiple-instances/index.html
ontotext-yasgui-web-component/src/pages/multiple-instances/main.js

Expose public methods which allows the component client to get the query mode and type.
Some implementations on the client side require the client to know the query mode and type.
* Exposed the new methods which delegate the task for resolving this information to the yasqe component.
* Additionally some organization in the main component was done.
Additionally:
* Added a fake server which allows more test cases to be easily executed in the example pages.
* Added an editorconfig file to allow more consistent formatting.

GDB-7890 expose get query mode and query type public methods

---

Yasgui/packages/yasr/src/extended-yasr.ts
cypress/e2e/yasr/download-as.spec.cy.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
yasgui-patches/2023-02-20-fixes-are-results-check.patch

GDB-7711 plugins issues
- There is outline styling on a plugin tab when it is focused.
- "Download as" dropdown is visible when there aren't results.
- Outline styling was set from client theme.
- Wrong check are there results.
- Removes outline from all "ontotext-yasgui" buttons.
- Fixes check if there are results.

GDB-7711 fixes extend table plugin issues

---

Yasgui/packages/yasr/src/extended-yasr.ts
Yasgui/packages/yasr/src/index.ts
cypress/e2e/yasr/download-as.spec.cy.ts
cypress/steps/download-as-page-steps.ts
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/download-as/download-as.scss
ontotext-yasgui-web-component/src/components/download-as/download-as.tsx
ontotext-yasgui-web-component/src/components/download-as/readme.md
ontotext-yasgui-web-component/src/components/dropdown/dropdown.scss
ontotext-yasgui-web-component/src/components/dropdown/dropdown.tsx
ontotext-yasgui-web-component/src/components/dropdown/readme.md
ontotext-yasgui-web-component/src/components/ontotext-tooltip-web-component/ontotext-tooltip-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-tooltip-web-component/readme.md
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts
yasgui-patches/2023-02-22-added_tooltip_to_plugins_tabs_buttons_.patch

Adds icon "download" to "Download as" dropdown. When screen is smaller than 768px only the icon will be visible. 
This will improve UX, and is consistent with plugin tabs names.
"Dropdown" component hase improved to support icon. Changed the setup of "Dropdown" component in "Download as" with download icon.

GDB-7891: add icon to "Download as" dropdown.

---

Yasgui/packages/yasqe/src/prefixFold.ts
yasgui-patches/2023-02-24_migrate_the_prefixFold_utility.patch

Migrate some of the applicable changes in the prefixFold utility.
The prefixFold.js utility has some changes in the old YASQE accounting bugs in the editor. Found that some of the changes are not needed because related bugs are not applicable in the latest YASQE anymore.
* Migrate prefixFold changes.

GDB-7763 migrate the prefixFold utility

---

Yasgui/packages/yasqe/src/defaults.ts
yasgui-patches/2023-02-24_3_migrate_yasqe_defaults_js_module.patch

Migrated the yasqe defaults.js module from old yasqe
There is new hot-key combination added in the module which allows autocompleter to be triggered.
* Registered the new hot-key combination.

GDB-7769 migrate yasqe defaults.js module

---

Yasgui/packages/yasqe/src/autocompleters/index.ts
Yasgui/packages/yasqe/src/autocompleters/sesame-prefixes.ts
Yasgui/packages/yasqe/src/defaults.ts
Yasgui/packages/yasqe/src/index.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts

Moved the sesame-autocompleter in yasqe.
This was needed because we had troubles compiling and running the ontotext-yasgui component when we imported whatever from the yasgui. This enforced us to move our addons in their codebase in order to be able to reuse their api functions properly without duplicating them on our side.
Just moved the autocompleter implementation and registered it.

GDB-7709 move sesame-prefixes autocompleter in yasqe

---

Yasgui/packages/yasqe/src/autocompleters/index.ts
Yasgui/packages/yasqe/src/autocompleters/sparql-functions.ts
yasgui-patches/2023-03-08_1-introduce_sparql_functions_autocompleter.patch

Introduced sparql functions autocomplete addon
This is a handy feature existing in current version of the WB where there is an autocomplete for standard sparql functions.
Migrated the standard.js autocomplete and registered as sparql-functions in yasqe.

GDB-8007 introduce sparql functions autocompleter

---

cypress/e2e/autocomplete/sesame-autocomplete.spec.cy.ts
cypress/fixtures/namespaces/sesame-prefixes-response.json
cypress/stubs/autocomplete-stubs.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/pages/autocomplete/index.html
ontotext-yasgui-web-component/src/pages/autocomplete/main.js
ontotext-yasgui-web-component/src/pages/fake-server.js
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
ontotext-yasgui-web-component/src/services/yasqe/autocompleter/local-names.ts

Implemented a local names autocompleter and registered in yasqe.
The autocompleter allows suggesting namespaces from the GDB instance to which the WB is connected.
Implemented the autocompleter and provided a new configuration allowing custom autocomplete functions to be provided by the component client.

GDB-7760 implement local-names autocompleter

---

Yasgui/packages/yasqe/src/defaults.ts
Yasgui/packages/yasqe/src/index.ts
Yasgui/packages/yasr/src/extended-yasr.ts
cypress/e2e/editor-actions/execute-query.spec.cy.ts
cypress/e2e/yasr/plugin-table.spec.cy.ts
cypress/steps/keyboard-shortcut-steps.ts
cypress/steps/pages/keyboard-shortcut-page-steps.ts
cypress/steps/yasqe-steps.ts
cypress/steps/yasr-steps.ts
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/pages/actions/main.js
ontotext-yasgui-web-component/src/pages/keyboard-shortcuts/index.html
ontotext-yasgui-web-component/src/pages/keyboard-shortcuts/main.js
ontotext-yasgui-web-component/src/services/keyboard-shortcut-service.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
yasgui-patches/2023-03-22-stop_execution_of_query.patch

Stops execution of a query when:
- try to execute explain plan query for update query;
- try to execute update query on virtual repository
- Explain plan query can be executed only for construct or select queries;
- Virtual repository can't be updated.
Added checks and if they not pass emits message to notify user about reason why query not executed.
- Fixes NPE localNamesLoader is not passed as configuration;
- Fixes "Uncaught TypeError" exception when query is rejected;
- Fixes broken test "Should emit queryExecuted event on each editor tab";
- Fixes broken "Execute query action" tests.

GDB-8020: stop execution of query

---

Yasgui/packages/yasgui/src/Tab.ts
Yasgui/packages/yasgui/src/closeTabConfirmation.ts
Yasgui/packages/yasgui/src/index.ts
cypress/e2e/defalt-view.spec.cy.ts
cypress/e2e/saved-query/delete-saved-query.spec.cy.ts
cypress/e2e/yasgui-tabs.spec.cy.ts
cypress/steps/confirmation-dialog.steps.ts
cypress/steps/yasgui-steps.ts
cypress/steps/yasqe-steps.ts
cypress/steps/yasr-steps.ts
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/confirmation-dialog/confirmation-dialog.tsx
ontotext-yasgui-web-component/src/components/confirmation-dialog/readme.md
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
yasgui-patches/2023-03-27_GDB-8036_GDB-8037_confirmation_on_tab_close_using_our_custom_confirmation_dialog.patch

Yasgui should ask the user for confirmation on yasgui tab close.
This prevents accidental loss of already written queries. Also if a query was ran, closing the tab would abort the query which might be unexpected.
* Plugged in our confirmation dialog component in yasgui tab when close operation get triggered.

GDB-8036 GDB-8037 ask for confirmation on yasgui tab close

---

Yasgui/packages/yasgui/src/Tab.ts
Yasgui/packages/yasr/src/extended-yasr.ts
Yasgui/packages/yasr/src/index.ts
Yasgui/packages/yasr/src/plugins/error/extended-error.ts
Yasgui/packages/yasr/src/plugins/error/index.ts
Yasgui/packages/yasr/src/plugins/response/extended-response.ts
cypress/e2e/languages.spec.cy.ts
cypress/e2e/yasr/download-as.spec.cy.ts
cypress/e2e/yasr/error-plugin.spec.cy.ts
cypress/e2e/yasr/plugin-raw-response.spec.cy.ts
cypress/steps/error-plugin-steps.ts
cypress/steps/yasr-steps.ts
cypress/stubs/query-stubs.ts
ontotext-yasgui-web-component/src/components/keyboard-shortcuts-dialog/keyboard-shortcuts-dialog.scss
ontotext-yasgui-web-component/src/components/ontotext-dialog-web-component/ontotext-dialog-web-component.scss
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/components/pagination/pagination.scss
ontotext-yasgui-web-component/src/css/_variables.scss
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts
yasgui-patches/2023-03-31-GDB-8105__YASR__Error_handling.patch

Added an error plugin that displays error messages when something goes wrong during query execution.
WB has such functionality that displays a message that describes to the user what the reason for which the exception occurred.
A new "extended_error" plugin is added. It has responsibility to displays the error messages that can be occurred during query execution.
Added error info to yasr persistence.
-Rename the registration name of the ExtendedResponse plugin to be similar like other extended plugins.
-Rename "$background-onto-default" to "$background-color-onto-default".
- Remove a test form language suite because, after error plugin implementation, it doesn't sense.

GDB-8105: YASR: Error handling

---

Yasgui/packages/yasgui/src/Tab.ts
Yasgui/packages/yasqe/src/index.ts
Yasgui/packages/yasqe/src/sparql.ts
Yasgui/packages/yasr/src/extended-yasr.ts
Yasgui/packages/yasr/src/index.ts
Yasgui/packages/yasr/src/parsers/index.ts
yasgui-patches/2023-04-03-GDB-8112_Skip_the_count_query_if_results_are_less_than_one_page.patch

Skips the count query when the results of fulfilled query are less or equal of the page size.
- Better performance;
- WB has such functionality.
Added checks after every one query and if returned results are less or equal of page size, then total elements are calculates depends on the current page, the page size and the count of results.
- "totalElementChanged" event name is renamed to "totalElementsChanged";
- "countQueryReady" event name is renamed to "totalElementsPersisted",

GDB-8112: Skip the count query if results are less than one page

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/models/output-events/count-query-event.ts
ontotext-yasgui-web-component/src/models/output-events/query-event.ts

Extends "QueryEvent" and "CountQueryEvent" event models to support the query type and the page size.
The client (WB) needs this information to set up correct request headers.
Extends the event payload to deliver required information.

GDB-8132: Add appropriate headers depending on query mode and type

---

Yasgui/packages/yasqe/src/index.ts
cypress/e2e/editor-actions/execute-query.spec.cy.ts
cypress/e2e/keyboard-shortcuts.spec.cy.ts
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
yasgui-patches/2023-04-27-GDB-8207_add_explain_plan_command_for_DESCRIBE_queries.patch

Extends the supported explain plan queries with a DESCRIBE query.
WB was extended to support explain plan for DESCRIBE query.
Extends restriction of supported queries of explain plan command.

GDB-8207: Add explain plan command for DESCRIBE queries

---

cypress/e2e/yasr/sparql-result-formatting.spec.cy.ts
cypress/fixtures/queries/single-iri-result.json
cypress/fixtures/queries/single-literal-with-data-type-response.json
cypress/fixtures/queries/single-literal-with-lang-tag-response.json
cypress/fixtures/queries/single-literal-without-lang-tag-response.json
cypress/steps/yasr-steps.ts
cypress/stubs/query-stubs.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts

When IRIs in SPARQL results are shown and don’t fit in the available column size they aren’t wrapped to the next line. This varies between browsers and versions.
Browsers have different defaults about word-wrapping.
Added word break rules depends on result binding type.
- For IRIs and blank nodes:
- adds word-wrap: break-word to all cell with IRI content;
- inserts at strategic places: after :, /, -, _ but treat sequences of those as one thing, e.g. http://example…;
- set attribute lang="xx" on the element.
- For literals:
- adds word-wrap: break-word to all cell with literal content;
- added hyphens: auto (+ -moz- and -webkit- prefixed version) to all cell with literal content;
- if the literal has a language tag;
- set attribute lang="" on the element;
- if literal without language tag; …

GDB-8247: Update results cells to not cut the long IRIs

---

Yasgui/packages/yasgui/src/Tab.ts
Yasgui/packages/yasr/src/index.ts
ontotext-yasgui-web-component/README.md
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts
yasgui-patches/2023-06-22_GDB-7730_Extends_yasgui_results_to_be_set_via_configuration.patch

- The OntotextYasguiWebComponent.getOntotextYasgui() function returns a promise with ontotextYasgui reference after 100ms without matter that the instance already exist.
- Expose getCellContent function to yasgui client;
- Expose yasrData
- The function uses "setInterval" with a time interval of 100ms, so the first check is after 100ms, and if instance exists, the promise with reference is returned.
- Added initial check if instance exists, if yes return it, if not then "setInterval" is used.
- Fixes GDB-8382

GDB-7730: integration with jdbc view.

---

Yasgui/packages/yasqe/src/sparql.ts
ontotext-yasgui-web-component/src/services/yasqe/autocompleter/local-names.ts
yasgui-patches/2023-07-04_Fixe_issues_caused_by_WB_.patch

- When use local name autocompleter;
- NPE when 'beforeUpdateQuery' returns no result.
- When autocomplete functionality is off then "localNamesLoader(query)" promise don't return suggestions;
- WB's beforeUpdateQuery implementation has rest call to backend server that can throw error in this case WB don't return  beforeUpdateQueryResult.
- added check if response contains suggestions;
- added check if beforeUpdateQueryResult is not undefined.

Fixed issues caused by WB.

---

Yasgui/packages/yasr/src/plugins/table/extended-table.ts
yasgui-patches/2023-07-07-GDB-8286_fixing_yasgui_results_rendering_performance_issue.patch

Fixes the rendering performance issue in our table renderer plugin extension in yasgui.
We observed that when say 1000 results has to be rendered in the yasr table, then it struggles to do it in a responsive manner. We noticed that it takes around 8 seconds which is beyond ideal. That's why we need to find a fix for the bottleneck.
* Reimplemented the setupIndexColumn function in the ExtendedTable plugin implementation to prevent redundant rerendering of the index column.

GDB-8286 fixing yasgui results rendering performance issue

---

ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-tooltip-web-component/ontotext-tooltip-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts

Expose a new method, which runs the yasqe query.
There are client flows where the query needs to be executed programmatically.
Added a new method 'query', to run the yasqe query.
Fixed a null pointer exception (NPE) that occurs when trying to set content but the tooltip is not yet initialized.

Extends the public Api of the component.

---

ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts
ontotext-yasgui-web-component/src/services/utils/visualisation-utils.ts

Expose a new method, which changes the rendering mode.
Changing the render mode used to only be possible through configuration changes, but this would result in destroying the instance and creating a new one. This is now avoided with the new method, where if the client invokes it, it will change the render mode without destroying the instance.
Expose a new method that changes the component render mode.
Fixes definition of "OntotextYasgui#query" function.

Extends the public Api of the component with new "changeRenderMode" function.

---

Yasgui/packages/yasgui/src/Tab.ts
Yasgui/packages/yasr/src/defaults.ts
Yasgui/packages/yasr/src/extended-yasr.ts
Yasgui/packages/yasr/src/index.ts
Yasgui/packages/yasr/src/parsers/index.ts
cypress/e2e/view-configurations.spec.cy.ts
cypress/steps/yasr-steps.ts
ontotext-yasgui-web-component/README.md
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/services/utils/html-elements-util.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
ontotext-yasgui-web-component/src/services/yasgui/ontotext-yasgui-service.ts
ontotext-yasgui-web-component/src/services/yasr/toolbar/pagination-yasr-toolbar-plugin.ts
yasgui-patches/2023-07-21-added-total-elements-to-response-object.patch

- I can't configure only pagination to be displayed.
- Pagination pages and total elements are not displayed when the result data size is more than the configured length with the "maxPersistentResponseSize" property.
The configuration isn't granular enough.
- The calculation of pagination pages and the result info message is based on the total element value, which is fetched asynchronously with a second request. When the total element is ready, its value is persisted to the browser's local store. However, if the response size is larger, the result is not persisted. As a result, the pagination functionality fetches undefined value of the total element. As a result, the pages and result info are not correctly displayed..
- Added a new configuration option "showResultInfo" to hide/show …

Extends component configuration

---

ontotext-yasgui-web-component/src/components/confirmation-dialog/confirmation-dialog.scss
ontotext-yasgui-web-component/src/components/confirmation-dialog/confirmation-dialog.tsx
ontotext-yasgui-web-component/src/components/copy-link-dialog/copy-link-dialog.scss
ontotext-yasgui-web-component/src/components/copy-link-dialog/copy-link-dialog.tsx
ontotext-yasgui-web-component/src/components/dropdown/dropdown.tsx
ontotext-yasgui-web-component/src/components/keyboard-shortcuts-dialog/keyboard-shortcuts-dialog.tsx
ontotext-yasgui-web-component/src/components/save-query-dialog/save-query-dialog.scss
ontotext-yasgui-web-component/src/components/save-query-dialog/save-query-dialog.tsx
ontotext-yasgui-web-component/src/components/saved-queries-popup/saved-queries-popup.tsx

* Reorganized the order of ok/cancel buttons in all dialogs in a way that the primary action button to be always on the right.
* Allow all dialogs and menus to be closed by hitting the [esc] keyboard key.
A decision was taken for the Ontotext workbench application where those buttons must have a consistent order and position throughout the application. Given that decision, here we need to apply the same rules in order to comply with the entire look'n'feel of the workbench. Also it was identified that having the option to close any dialog or menu by clicking the [esc] key would lead to a better user experience.
* Changed the buttons order.
* Implemented listeners allowing to close dialogs and menus on [esc] keydown event.

GDB-8598 reorganize ok/cancel button positions in dialogs and allow dialogs and menus to be close via [esc] keydown

---

Yasgui/packages/yasgui/src/index.ts
ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts
yasgui-patches/2023-08-10-changed_algorithm_of_opening_tab.patch

A new tab is opened although there is a tab with same name and query.
The algorithm of finding the tab with same name and query looking for first tab with same name checks the query and if query not same opens a new tab, but if there could be a second tab with same name and looked for query, in this case opening a new tab is wrong.
Changed algorithm to not stop after first found tab with same name but different query.

Changed algorithm of opening tab

---

Yasgui/packages/yasgui/src/index.ts
Yasgui/packages/yasqe/src/index.ts
cypress/e2e/keyboard-shortcuts.spec.cy.ts
cypress/steps/yasr-steps.ts
ontotext-yasgui-web-component/README.md
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
yasgui-patches/2023-08-15-make_external_extra_key_configuration_to_override_defaults.patch

When the component is configured to hide the query run button, some shortcut keys that execute queries remain active.
Yasqe has a default configuration of shortcut key functions, and those functions are merged with externally passed functions. However, when the external configuration doesn't provide an execution function, the default one is used.
The behavior of the 'extraKeys' configuration is changed. The old implementation, which merged the external and default configurations, has been replaced with a new one where the external configuration overrides the internal one.

Fixes Yasqe Shortcut Key Functionality

---

Yasgui/packages/yasr/src/extended-yasr.ts
cypress/e2e/yasr/plugins/table/copy-link-dialog.spec.cy.ts
yasgui-patches/2023-08-16-fixes_slow_rendering_of_extended_table_plugin.patch

- When the SPARQL view is opened, and the active tab contains a significant number of results, the page becomes unresponsive until YASR finishes rendering.
- When run a query the YASR results are rendered slowly.
- The rendering process of YASR is synchronous and can be time-consuming, particularly when handling a large volume of results.
- When the pagination functionality was implemented, two event listeners were registered to update the pagination. The implementation of these event handlers simply called the YASR draw function. However, this function is slow due to its rendering of the result table. As a result, for a single query execution, the function is called three times: once from the original YASGUI implementation and twice from both listeners.
- To address this issue, the …

GDB-8286: The `ontotext-yasgui-web-component` opens slowly when there are many results.

---

Yasgui/packages/yasr/src/plugins/table/index.ts
yasgui-patches/2023-08-16-GDB-8626_allow_yasr_table_columns_to_be_resized_from_any_row.patch

Allow yasr table columns to be resizable from any table row.
The old yasgui integrated in the GDB workbench was configured to allow such behavior and we want it to come as a default with the new component.
Changed the configuration passed to the ColumnResizer plugin to the datatable.

GDB-8626 allow yasr table columns to be resized from any row

---

Yasgui/packages/yasgui/src/Tab.ts
Yasgui/packages/yasgui/src/TabElements.scss
Yasgui/packages/yasgui/src/TabElements.ts
Yasgui/packages/yasgui/src/index.ts
Yasgui/packages/yasqe/src/index.ts
cypress/e2e/yasgui-tabs.spec.cy.ts
cypress/steps/yasgui-steps.ts
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
yasgui-patches/2023-08-17-GDB-8626_show_error_mark_on_yasgui_a_tab_when_query_is_invalid.patch

Show an error mark on the yasgui tab when the query inside its editor is invalid.
In the old implementation in the GDB workbench was implemented such behavior and we want it here as well.
Implemented a new event queryStatus fired by yasqe and propagated to TabsList component where it's possible to update the respective tab by adding a marker css class and a title message.

GDB-8626 show error mark on yasgui a tab when query is invalid

---

Yasgui/packages/yasgui/src/Tab.ts
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
yasgui-patches/2023-08-22-tab_is_not_visible_when_execute__Close_other_tabs__command_.patch

When the closeOtherTabs function is called, all other tabs are closed, but the YASQE and YASR sections of the active tab are dismissed. Only the tab with the tab name is left.
The close function of the Tab object has been changed during development. I don't know why, but destroying of active tab has been added, that removes all content of the active tab.
The incorrect destruction of the active tab has been removed.
The description of the 'Close Other Tabs' keyboard shortcut has been changed.

GDB-8194: Tab is not visible when execute "Close other tabs" command.

---

Yasgui/packages/yasr/src/main.scss
Yasgui/packages/yasr/src/plugins/error/extended-error.ts
yasgui-patches/2023-08-23-fixes_some_visual_issues.patch

- [GDB-8684](https://ontotext.atlassian.net/browse/GDB-8684) Changed Minimum Height of the Container Holding the YASR Plugin Buttons
- [GDB-8191](https://ontotext.atlassian.net/browse/GDB-8191): Changed formatting of error message
- When [GDB-8684](https://ontotext.atlassian.net/browse/GDB-8684) was implemented, the component was configured to display result info that didn't have a result info message. As a result, the toolbar appeared small and unattractive;
- The error message has extra spaces.
- In cases where there's no result message, the minimum height of the container was not being set;
- The 'createErrorMessageElement' function builds the error message elements as html string using Template literals. The template literal allow new lines and white space characters to be added to …

Fixes visual issues

---

ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/services/yasr/toolbar/download-as-yasr-toolbar-plugin.ts

Added support for ND-JSONLD file formats
To enhance the download compatibility and usability, this commit introduces support for ND-JSONLD file format
- added ND-JSONLD entry in the list of options

GDB-8281 add ND-JSONLD rdf file format to download formats

---

ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts

A Null Pointer Exception (NPE) occurs when attempting to create a new tab without passing a TabQueryModel parameter.
There was no null check in the function.
A null check has been added.

Fixes npe when try to create a tab without pass query parameter

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts

When hovering over a URI in Yasr, the "Copy URL to clipboard" button is not visible in the Firefox browser.
The CSS selector that displays the URI includes a ":has" selector, which is not supported by the Firefox browser.
Simplify the selectors that display the copy button.

GDB-8185: Тhe button for "Copy URL to clipboard" is not visible on Browser Firefox

---

Yasgui/packages/yasr/src/plugins/error/extended-error.ts
Yasgui/packages/yasr/src/plugins/error/index.ts
cypress/e2e/yasr/plugins/error/error-plugin.spec.cy.ts
cypress/steps/error-plugin-steps.ts
cypress/stubs/query-stubs.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
yasgui-patches/2023-10-17-update_error_plugin.patch

When exception is thrown after executing of sparql query, the workbench shows the error. But if the error is too big the error area is too long. Most of the users do not need to see the entire message.
WB displays all error messages no matter of its length.
Added functionality that checks error message length and if it is too long a small part of message is displayed accompanied by a 'Show full error message' button to expand it. When the button is clicked all error will be displayed accompanied by a 'Show less error message' button to show less part of message.

GDB-8438: YASR: Update error plugin

---

Yasgui/packages/yasr/src/index.ts
ontotext-yasgui-web-component/README.md
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
yasgui-patches/2023-10-19-removes-unnecessary-drawing-of-yasr-plugins.patch

- Introduce a new configuration property "language";
- There was double rendering of  yasr selected plugin when page is open or active tab is changed.
- There was no way to set the language when the component is created. The default language was English, so if the client wanted to open the component with French, for instance, they had to open it with English and then refresh it as set language on French. This flow caused component to be redrawn twice;
- When the yasr is created depends on parameters the function "setResponse" is called. Inside this function the draw method of yasr is called which draws active plugin. After that when all tabs are initialized the active tab is marked as "Active" when tab is marked as active the draw method is called for second time.
- When the component is …

Gdb 8286 the ontotext yasgui web component is open slowly when there are many results

---

Yasgui/packages/yasr/src/plugins/table/index.ts
yasgui-patches/2023-10-24-GDB-8184_he_columns_are_not_proportional.patch

After rendering a response in YASR, clicking on 'Simple view' causes the column widths to change, making them non-proportional.
YASR relies on 'column-resizer' to calculate the column widths. However, an issue arises due to incorrect calculations of column widths before creating the resizer.
The 'width' configuration of 'column-resizer' has been removed. Now, the browser itself calculates the column widths.

GDB-8184: The columns are not proportional

---

cypress/e2e/yasr/plugins/pivot-table/pivot-table-plugin.spec.cy.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/plugins/yasr/pivot-table/pivot-table-plugin.ts

A "Chart Config" button has been added.
This will provide an opportunity to configure the chart visualization of the response. This will provide an opportunity to configure the chart visualization of the response.
A "Chart Config" button has been added. When the button is clicked, a Google chart editor for configuring the selected chart is opened.

GDB-7790: Add "Chart Config" button when a chart render is chosen

---

cypress/e2e/yasr/plugins/pivot-table/pivot-table-plugin.spec.cy.ts
ontotext-yasgui-web-component/src/plugins/yasr/pivot-table/pivot-table-plugin.ts

Frequently, an error "Cannot read properties of undefined (reading 'arrayToDataTable')" occurs when a Google chart render is selected, and the page is refreshed.
The Google visualization module loads asynchronously to the pivot table plugin code. When a Google chart render is selected and the pivot table try to render result before visualization module loaded the exception is thrown.
The code has been modified to wait for the Google visualization module to load before rendering results if the selected render is a Google chart.
Optimized the loading of the Google visualization module. Added a check to ensure the module is not loaded again.

GDB-7790: There is render error when Google chart render selected

---

cypress/e2e/yasr/toolbar/yasr-toolbar.spec.cy.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/css/charts-plugin.scss
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/yasr-toolbar-plugin.ts
ontotext-yasgui-web-component/src/models/yasr.ts
ontotext-yasgui-web-component/src/plugins/yasr/charts/charts-plugin.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
ontotext-yasgui-web-component/src/services/yasr/toolbar/chart-download-plugin.ts

Introduce download for chart plugin when datatable is rendered in csv format and svg snippet when chart is rendered.
This would allow users to export the result from the quer in the respective format or as svg for embedding in some html page.
* Implemented a plugin for the download operation in yasr toolbar.
* Implemented the download method to extract and return the appropriate data for download depending on what visualization is selected in the chart plugin.

GDB-7789 allow download of chart plugin data

---

Yasgui/packages/yasr/src/extended-yasr.ts
yasgui-patches/2023-11-08-GDB-7789_put_yasr_toolbar_info_message_in_separate_tag_to_allow_customization_on_client.patch

Put yasr toolbar info message in separate tag to allow customization on client side
On the client side this message can't be moved separately if we put other elements in this section like the chart config button for example.
* Wrap the info message in its own tag with a css class to allow easier customization.

GDB-7789 put yasr toolbar info message in separate tag to allow customization on client side

---

ontotext-yasgui-web-component/src/plugins/yasr/pivot-table/pivot-table-download-util.ts

Values that don't have to be escaped missed in exported CSV file.
Missed return statement in function that have to escape values.
The return statement has been added.

GDB-7790: There missing values in CSV export

---

ontotext-yasgui-web-component/src/components/dropdown/dropdown.tsx
ontotext-yasgui-web-component/src/services/yasgui/ontotext-yasgui-service.ts

When `showResultTabs` flag is set to `false` then all yasr plugins should be hidden.
There are some integration points where only the yasr results table renderer is displayed and no tabs should be visible. In the latest version of this component were introduced two new yasr plugins: charts and pivot table. These two plugins were not registered in the service which used to hide them when the flag is falsy.
Added the plugins in the list where they are shown or hidden conditionally.

GDB-9118 hide all yasr plugin tabs if configured via showResultTabs

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts

Improve styling of yasr table results.
Cells holding literal values were not styled correctly to apply the ellipsis which resulted in value being cut off.
Improved the styling of the paragraphs inside literal cells in order for the ellipsis to work and also applied a title attribute to them so that when the value gets truncated, the user to still be able to see the whole value.

GDB-8247 improve styling of yasr table results

---

ontotext-yasgui-web-component/src/components/dropdown/dropdown.scss
ontotext-yasgui-web-component/src/components/saved-queries-popup/saved-queries-popup.scss

* Fix download as menu styling for consistency with old yasgui.
* Reposition yasqe action buttons to prevent overlapping with the vertical scrollbar when it's present in the yasqe.
* The dropdown menu items padding and font size were left default as in the ontotext yasgui component which resulted in different menu and menu items size.
* Yasqe buttons were placed too close to the right-side border of the editor which led to overlapping between the vertical scrollbar and the run query button.
* Overriding the menu items padding and font-size properties.
* Increased the space between the buttons and the right-side editor border

GDB-8994 GDB-9114 improve yasr styling

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts

Properly break literal values on new lines in yasr table when string too wide to accommodate on a single line.
This is the way how literal values are rendered in the graphdb yasr
* Changed the word-break to normal and added a white-space pre-wrap to allow browser to break the text properly

GDB-8247 properly break literal values in yasr table

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/plugins/yasr/charts/charts-plugin.ts
ontotext-yasgui-web-component/src/plugins/yasr/pivot-table/pivot-table-plugin.ts

Move chart config button in the beginning of the yasr header.
After yasr header reorganization these buttons were left unchanged which was wrong because in the current workbench they appear in the beginning of the header.
Put buttons in container and append it in the beginning of the yasr header.

GDB-8997 move chart config button in the beginning of the yasr header

---

ontotext-yasgui-web-component/src/services/utils/html-util.ts
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts

When execute explain plane query the result look like plane text. When page is resized it is rendered as expected.
The value of result is escaped differently than old version of yasr, and the new escaping function brokes somehow rendering the view.
The escaping function has been changed to be like old implementation.

GDB-9168: Wrong styling of explain plan

---

Yasgui/packages/yasr/src/main.scss

There is no space between the "Visual" button and the "Get HTML snippets..." button in the "Pivot Table" and "Charts" plugins.
This issue is caused by incorrect styling.
Margins on the left and right of the "yasr-toolbar-element" elements have been added to resolve the spacing problem.

GDB-9146: The button Visual in tab Pivot table and Google tab should have a distance with the button GET HTML

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx

Prevent tab duplication when saved query is selected.
When a saved query is selected from the menu, then a new tab is opened each time instead of focusing on the existing opened tab with the same name and query inside. This is unexpected behavior.
Just used the openTab method which has the ability to properly resolve this behavior instead of opening a new tab.

GDB-9231 prevent tab duplication when saved query is selected

---

ontotext-yasgui-web-component/src/models/yasr.ts
ontotext-yasgui-web-component/src/plugins/yasr/charts/charts-plugin.ts
ontotext-yasgui-web-component/src/plugins/yasr/pivot-table/pivot-table-plugin.ts

Remove the chart config button when changing yasr tabs
Chart config button remains visible when changing from google chart or pivot table to some of the other yasr tabs which should not happen.
Extended the destroy function in the google chart and pivot table plugins to remove the button.

GDB-9230 remove chart config button when changing yasr tabs

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss

Refactor yasgui layout to work properly when horizontal ordering is selected.
When horizontal ordering is selected, yasqe and yasr should be aligned next to each other and both span 50% of the screen width even if there is a  query containing very long lines.
* Made the yasqe and yasr be floated in the left and span 50% of the screen width. This replaces the old approach which aligned them using grid layout which doesn't seem to work and scale properly.
* Also made the yasr container be absolute positioned and aligned top along with the yasgui's top border in order to align the yasr and yasqe tabs pproperly.

GDB-9245 refactor yasgui layout to work properly when horizontal ordering is selected

---

cypress/e2e/view-modes.spec.cy.ts
cypress/steps/yasqe-steps.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/services/utils/visualisation-utils.ts
ontotext-yasgui-web-component/src/services/yasgui/ontotext-yasgui-service.ts

Refactor yasgui component layout to work properly when rendering mode or orientation are changed.
When switching to vertical layout yasqe should span the entire height of the viewport. Same should happen also when the yasqe mode (editor only) mode is selected.
* Refactored the component to call an utility function which is capable of calculating the possible height which the yasqe could have and applying it.
* Introduced a renderingMode state property which holds the actual rendering mode. This was needed in order to allow getting the actual value instead of resolving the one that comes from the config.
* Extended the tests to cover some ot the corner cases related with this functionality.

GDB-8995 refactor yasgui component layout to work properly when rendering mode or orientation are changed

---

cypress/e2e/before-execute-query.spec.cy.ts
cypress/e2e/editor-actions/abort-query.spec.cy.ts
cypress/e2e/editor-actions/execute-query.spec.cy.ts
cypress/e2e/view-modes.spec.cy.ts
cypress/e2e/yasgui-toolbar.spec.cy.ts
cypress/steps/yasqe-steps.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx

Rendering mode should be switched to yasgui when query is run.
This is the expected behavior and the workbench works this way. The user would expect when executing a query to see the results even if he previously switched to editor only mode.
* Switch the rendering mode from the internal query run event.
* Added test and fixed a typo in some of the test steps.

GDB-8995 rendering mode should be switched to yasgui when query is run

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts

Preserve cursor position when query is set in the editor.
There was a bug where when the setQuery method was invoked, the query was set in the editor but this was resetting the cursor to initial position in the beginning of the editor.
Applied a fix where the cursor position is stored locally and after setting the query it's then restored to its previous position.

GDB-8993 preserve cursor position when query is set in the editor

---

ontotext-yasgui-web-component/src/plugins/yasr/pivot-table/pivot-table-plugin.ts
yasgui-patches/2023-11-28-GDB-9146_missing_space_between_yasr_toolbar_elements.patch

Increase the d3 version.
WB increased the version of the d3 library, causing a problem with the ontotext-yasgui-web-component version.
The d3 library version was increased.
Added "2023-11-28-GDB-9146_missing_space_between_yasr_toolbar_elements.patch" patch because, the changes made for GDB-9146 issue has changes inside original yasgui, they were merged without to creating of a patch for that changes.

GDB-9145 visual graph cannot open via sparql view

---

Yasgui/packages/utils/src/index.ts
Yasgui/packages/yasqe/src/autocompleters/index.ts
Yasgui/packages/yasqe/src/index.ts
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/services/translation.service.ts
yasgui-patches/2023-12-5_Fixes_Translation_of_Autocomplete_Hint_When_Language_is_Changed.patch

- Changed the translation of autocomplete hint "Press CTRL - <spacebar> to autocomplete." to "Press Alt+Enter to autocomplete";
- The TranslationService has been extended with a new "onTranslate" functions. It gives opportunity to service clients to subscribe to translation changes. The calling of "onTranslate" function will subscribe the caller for translation of given label. When the translation changed the caller will be notified with new translation;
- When the language is changed, the autocomplete label does not update.
- To be same as old Yasgui;
- Until now we don't have functionality to change labels dynamically. When we want to change the translations we just refresh all components. Which is slowly and not effective way to do that;
- We don't have dynamically changing of …

GDB-8645: Keyboard shortcuts differences between old implementation

---

cypress/e2e/keyboard-shortcuts.spec.cy.ts
cypress/steps/pages/keyboard-shortcut-page-steps.ts
ontotext-yasgui-web-component/README.md
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/keyboard-shortcut-description.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/pages/keyboard-shortcuts/index.html
ontotext-yasgui-web-component/src/pages/keyboard-shortcuts/main.js
ontotext-yasgui-web-component/src/services/keyboard-shortcut-service.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts

Expose a new configuration that controls which keyboard shortcuts are active.
Not all keyboard shortcut functions are related to ontotext-yasgui-web-component, there are two that are specific to WB. With this configuration, other client will have the opportunity to disable them.
Exposed a new configuration to the clients of the component.

Expose a new configuration

---

ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/alert-box/alert-box.scss
ontotext-yasgui-web-component/src/components/alert-box/alert-box.tsx
ontotext-yasgui-web-component/src/components/alert-box/readme.md

Introduce an alert box component which can be used in the yasgui.
There cases where there is a need to render such alert box. For example rendering warnings inside yasr when some plugin has some errors to show.
Implemented a new component.

GDB-9147 introduce an alert box component

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss

Position the query button at the bottom of the editor.
For consistency with the current workbench.
Applied css to absolutely position the button at the bottom which allows it to stay there even when the editor gets resized.

GDB-9267 position the query button at the bottom of the editor

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/index.html
ontotext-yasgui-web-component/src/pages/fake-server.js
ontotext-yasgui-web-component/src/pages/multicolumn-results/index.html
ontotext-yasgui-web-component/src/pages/multicolumn-results/main.js

Make datatable horizontally scrollable. Also improve the copy uri link positioning on narrow collumns.
* When query returns too many columns or the horizontal screen size too narrow to accommodate all the columns properly the table needs to have a horizontal scrollbar to allow easy access and visibility to all results.
* Also when columns are too narrow, then the styling applied to the copy link used to stretch the cell and thus the table column which looked ugly.
* Made the table layout to be auto instead of fixed to allow browser to calculate the column widths properly and horizontal scrollbar to appear.
* Changed the style of the copy link so that it is absolute positioned to prevent stretching the table cells.

GDB-9142 make datatable horizontally scrollable

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/models/yasgui/yasgui.ts
ontotext-yasgui-web-component/src/services/utils/html-elements-util.ts

Add a hint to autocomplete dropdown menu.
This would allow the user to better use the autocomplete functionality. Also this is present in the current workbench.
Hook into autocomplete show/hide events fired by the yasgui and rendered the hint component above the autocomplete dropdown.

GDB-9004 add a hint to autocomplete dropdown

---

Yasgui/packages/yasgui/src/TabElements.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss

- The "Add New Tab" button differs from the one in Workbench;
- The Context menu styling does not match any style in workbench.
- The "Add New Tab" button previously had the default YASGUI styling and had not been customized.
- The styling was default for the new YASGUI and had not been modified.
- Changed styling of the "Add new tab button";
- The style has been changed to look like left side menu.

GDB-8984: Style Changes for "Add New Tab" Button and Context Menu

---

cypress/e2e/editor-actions/rename-tab.spec.cy.ts
cypress/steps/yasgui-steps.ts
ontotext-yasgui-web-component/src/components/ontotext-editable-text-field/ontotext-editable-text-field.component.tsx

When renaming a tab and pressing the "Enter" key, the tab name is not persisted.
This functionality was not implemented.
Added a listener for the 'keydown' event that saves the tab name if the pressed key is "Enter."

GDB-9308: When I rename a tab name I should be able to save the changes with "Enter" key

---

Yasgui/packages/yasgui/src/extended-TabElements.ts
yasgui-patches/2024-01-02-GDB-9309_when_I_change_the_order_of_open_tabs_in_Sparql_view_and_switch_to_another_view.patch

The tabs disappear when the order of tabs is changed, and the page is refreshed.
There is an issue with fetching tab names in the "deriveTabOrderFromEls" function of "ExtendedTabListEl." When the element is created the id is prefixed with "tab-", but a different prefix, "tag-", is used when fetching the tab name from the id. This is causing the described issue.
Fixed the difference in prefixes used when creating the tab element and fetching the tab id.

GDB-9309: When I change the order of open tabs in Sparql view and switch to another view, the opened tabs are closed

---

ontotext-yasgui-web-component/src/components/keyboard-shortcuts-dialog/keyboard-shortcuts-dialog.scss

Center keyboard shortcut descriptions in their dialog.
For better perceiving and consistency with current workbench.
Changed the column widths in the dialog styles.

GDB-9002 center keyboard shortcut descriptions

---

Yasgui/packages/yasr/src/plugins/table/index.ts
yasgui-patches/2024-01-03-GDB-9143_Fixes_an_issue_with_the_resizing_of_YASR_table_columns.patch

When the YASR "Table" plugin renders a SPARQL query result the column resizing does not work until a column header is clicked.
The table columns are not rendered before the table-resizer is initialized.
The initialization of the table resizer has been wrapped in a setTimeout, ensuring that the resizer will render after the result table is rendered.
Configures the table resizer to exclude resizing the column number.

GDB-9143: Fixes an issue with the resizing of YASR table columns.

---

cypress/e2e/editor-actions/rename-tab.spec.cy.ts
cypress/steps/yasgui-steps.ts
ontotext-yasgui-web-component/src/components/ontotext-editable-text-field/ontotext-editable-text-field.component.tsx

Cancel tab renaming when the 'Escape' key is pressed.
There is such behaviour in the old implementation.
Added a listener for the "Escape" button press event, canceling tab renaming when the event is fired.

GDB-9308: cancel tab renaming

---

ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts

Fix literal cell content building.
Currently the function which processes the literal values uses a regex which incorrectly inserts <wbr> tags inside the </sup> tags which breaks the html.
Fix the regex to prevent inserting the <wbr> tag in such places.

GDB-8247 fix literal cell content building

---

ontotext-yasgui-web-component/src/components/copy-link-dialog/copy-link-dialog.scss
ontotext-yasgui-web-component/src/components/copy-link-dialog/copy-link-dialog.tsx
ontotext-yasgui-web-component/src/components/ontotext-dialog-web-component/ontotext-dialog-web-component.scss

The buttons in the "Copy link" dialog were frequently clickable and fully functional but not visible.
The problem was caused by a transition set on the buttons with "transition: all .15s ease-out," making the buttons invisible. This issue occurred only in Chrome.
Removed the problematic transition property.
Moved the styling for the cancel and copy buttons from "Ontotext-dialog-web-component.scss" to "copy-link-dialog.scss. Both buttons are part of the copy link dialog, and their styling should be in this component instead of the generic one.

GDB-9115: Fixed randomly invisible buttons of copy link buttons.

---

ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts
ontotext-yasgui-web-component/src/models/yasgui/yasqe.ts

When I edit the query and refresh the page without execute the query, the query is not persisted.
This functionality was not present in the new YASGUI version.
Added a "beforeunload" event handler. When the event occurs, the YASQE is triggered to execute the query persistence.

GDB-8646: save query changes on refresh

---

Yasgui/packages/yasr/src/plugins/table/index.ts
cypress/e2e-flaky/yasr/plugins/table/copy-link-dialog.spec.cy.ts
cypress/e2e/yasr/plugins/raw/plugin-raw-response.spec.cy.ts
cypress/e2e/yasr/plugins/table/plugin-table.spec.cy.ts
cypress/e2e/yasr/plugins/table/resize-columns.spec.cy.ts
cypress/steps/pages/yasr-plugin-page-steps.ts
cypress/steps/yasr-steps.ts
cypress/steps/yasr-table-plugin-steps.ts
ontotext-yasgui-web-component/README.md
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/pages/yasr-plugins/index.html
ontotext-yasgui-web-component/src/pages/yasr-plugins/main.js
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts
yasgui-patches/2024-01-15-GDB-9335_disable_column_resizing.patch

Disabled column resizing.
Column resizing functionality is slow and memory-consuming. If there are many cells to be displayed, the browser starts working slowly and frequently crashes.
The column resizer has been displayed.

GDB-9335: Disable column resizing.

---

Yasgui/packages/yasqe/src/index.ts
cypress/e2e/view-modes.spec.cy.ts
cypress/steps/view-mode-page-steps.ts
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/pages/view-modes/index.html
ontotext-yasgui-web-component/src/pages/view-modes/main.js
ontotext-yasgui-web-component/src/services/utils/visualisation-utils.ts

- When the "Run" button is not visible the last yasqe button is on the bottom of the editor;
- When executing a query, the view mode is changed to "RenderMode.YASGUI" (both YASQE and YASR are visible).
- With implementation of [GDB-8995](https://ontotext.atlassian.net/browse/GDB-8995) we added a style to displays
the last element of yasqe to be always on the bottom of the yasqe editor with assumption that the last element is the "Run" button, but this is not right, there are scenarios;
- We implemented this functionality with [GDB-8995](https://ontotext.atlassian.net/browse/GDB-8995), because this is expected behaviour. However, there are scenarios where YASGUI needs to be switched to another view, such as the test query of WB similarity view.
- Changed the style of the last YASQE button …

GDB-9310: Long yasqe screen with useless buttons in SQL table configuration

---

Yasgui/packages/yasgui/src/Tab.ts
Yasgui/packages/yasgui/src/index.ts
Yasgui/packages/yasr/src/index.ts
cypress/e2e/view-configurations.spec.cy.ts
cypress/e2e/yasr/plugins/charts/configure-charts.spec.cy.ts
cypress/e2e/yasr/plugins/raw/plugin-raw-response.spec.cy.ts
cypress/steps/pages/public-api-page-steps.ts
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/alert-box/alert-box.tsx
ontotext-yasgui-web-component/src/components/alert-box/readme.md
ontotext-yasgui-web-component/src/components/loader-component/loader-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/index.html
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts
ontotext-yasgui-web-component/src/models/yasgui/yasgui.ts
ontotext-yasgui-web-component/src/models/yasgui/yasr.ts
ontotext-yasgui-web-component/src/pages/public-api/index.html
ontotext-yasgui-web-component/src/pages/public-api/main.js
yasgui-patches/2024-01-17-GDB-8643_allow_yasr_results_to_be_cleared_and_to_show_a_warning_message_when_there_are_no_results.patch

Expose method for reseting the results rendered in yasgui.
This is needed for situations where for example as in the workbench the repository can be switched and then the results visible in the yasgui would become irrelevant.
* Expose method in the yasgui component which can be used to trigger the results reset.
* Implemeneted the logic in the yasgui and yasr components where the results are removed from the persistence in memory and the tab change is triggered in order to propagate the changes to the storage.

GDB-8643 handle repository change

---

Yasgui/packages/yasgui/src/extended-TabElements.ts
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-editable-text-field/ontotext-editable-text-field.component.tsx
ontotext-yasgui-web-component/src/components/ontotext-editable-text-field/ontotext-editable-text-field.scss
ontotext-yasgui-web-component/src/components/ontotext-editable-text-field/readme.md
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
yasgui-patches/2024-01-18-GDB-8984_added_tooltips_to_save_cancel_rename_tag_buttons.patch

- When opening "ontotext-editable-text-field" in edit mode, the buttons are positioned outside its container;
- When opening "ontotext-editable-text-field" in preview mode, the tab name and close button are not properly aligned;
- When hovering over the "Close tab" and "Add tab" icons, they do not resemble the appearance of the old version in Workbench;
- The cancel icon X on edit is different from the old version;
- When opening the "ontotext-edit-text-field," everything below is pushed down;
- Added a bottom border to inactive tabs when hovered.
- With the fix for GDB-9374, we added max-width to the component to trigger ellipsis of the component value. However, this somehow disrupts the calculation of input width within the flex container;
- There was improper styling;
- The size and …

Gdb 8984 fixes styling of tabs

---

Yasgui/packages/yasqe/src/defaults.ts
cypress/e2e/keyboard-shortcuts.spec.cy.ts
cypress/stubs/constants.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
yasgui-patches/2024-01-18-Increased_the_indent_spaces_in_SPARQL_editor.patch

Increased the indent spaces in SPARQL editor
Increased the number of indent spaces.
The codeMirror instance is created without configuration for indent spaces, and the default value is 2 spaces.
Added the configuration "indentUnit" with a value of 4.

Increase default spaces in sparql editor

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/pages/view-modes/index.html
ontotext-yasgui-web-component/src/pages/view-modes/main.js
ontotext-yasgui-web-component/src/services/utils/html-elements-util.ts

Reposition autocomplete hint to prevent overlapping with the current line in editor.
When the hint appears, in some cases it might overlap with the current line where the user types in the editor.
Reposition the autocomplete dropdown and the hint element a bit below the current line.

GDB-9004 reposition autocomplete hint to prevent overlapping with the current line in editor

---

ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts
ontotext-yasgui-web-component/src/models/output-events/output-event-types.ts
ontotext-yasgui-web-component/src/models/output-events/saved-query-opened.ts

- Exposed a new event "saveQueryOpened" that returns the instance of the opened tab;
- Extended the method "openTab" to return the instance of the opened tab.
To provide clients with the opportunity to interact with the opened instance. For instance, Workbench has functionality that highlights the tab name in red when a tab is opened from saved queries.
The code is modified to return the instance of the opened tab.

GDB-9338: When opening a saved query, there should be a very brief highlighting of the tab name in red

---

Yasgui/packages/yasr/src/extended-yasr.ts
Yasgui/packages/yasr/src/index.ts
cypress/e2e/yasr/query-loader.spec.cy.ts
cypress/steps/yasr-steps.ts
cypress/stubs/query-stubs.ts
ontotext-yasgui-web-component/src/components.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/readme.md
yasgui-patches/2024-01-22-GDB-9414_dont_hide_loader_when_query_is_running_and_show_proper_message_before_showing_it.patch

Preserve the query loader indicator while query is running.
* There was a case where switching the tab while the indicator was visible and then going back to the tab with the running query, then the loader wasn't rendered as expected.
* Also improved the code for showing the loader with a proper message when query was still in progress.
* Added check for running query before hiding the loader.
* Added a check for running query before rendering the loader and added proper message in the loader.

GDB-9414 preserve the query loader indicator while query is running

---

Yasgui/packages/yasgui/src/index.ts
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
yasgui-patches/2024-01-24-Remove_the_restriction_of_opening_a_new_tab_when_a_query_is_run.patch

Removed the restriction that controlled the opening of a new tab when a query is run.
The new YASGUI has a separate instance for each tab with YASQE and YASR, allowing us to safely run concurrent queries on different tabs.
The functionality that prevented the opening of a tab when a query is run has been removed.

Remove the restriction of opening a new tab when a query is run

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx

Expand yasqe after query is executed when yasgui is in two column layout.
For consistency with current workbench.
Invoke the utility which calculates and sets  the yasqe height after query was run.

GDB-9414 expand yasqe after query is executed when yasgui is in two column layout

---

ontotext-yasgui-web-component/.eslintrc.json
ontotext-yasgui-web-component/src/plugins/yasr/pivot-table/d3_7_8_5_renders.js
ontotext-yasgui-web-component/src/plugins/yasr/pivot-table/pivot-table-plugin.ts

The Treemap render for the pivot-table plugin is not working.
The implementation of the Treemap render relies on the d3 functionality. The d3 library was updated to version 7.8.5, but the render is implemented for an older version of d3, and there is no new implementation. That's why there is an error and render not working.
Implemented a render that works with the new version of the d3 library.

GDB-9277: Implement treemap render for pivottable plugin

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss

- When expanding some columns in the result table, the table overflows its parent container;
- The width of the first column is not set properly when columns are not resizable and the number column is hidden.
- The overflow properties were not set;
- When the result table becomes unresizable, we set a fixed width for columns by CSS, excluding the first column for row numbers. However, the selector skips the first column even when the numbers column is hidden, causing the issue.
- Added the necessary overflow properties;
- Changed the selector to now include all `<td>` elements that do not have the class "rowNumber" (this class is applied to row number `<td>` elements).

GDB-9360_GDB-9431 fixes css issues

---

Yasgui/packages/yasr/src/plugins/table/extended-table.ts
Yasgui/packages/yasr/src/plugins/table/index.scss
Yasgui/packages/yasr/src/plugins/table/index.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
yasgui-patches/2024-01-26-рefactoring_the_hide_row_number_functionality_GDB-9449_sparql_results_checkboxes_do_not_persisted.patch

When refreshing the SPARQL view ,the checkboxes for "Hide row numbers" and "Compact view" are reset to their default values, disregarding user changes.
The plugin configurations are persisted with a key using their plugin name. We use "extended_table" instead of "table" (the original YASGUI plugin) as it extends the table plugin. The plugin stores the configuration in "handleSetEllipsisToggle", "handleSetCompactToggle", and "handleTableSizeSelect" functions, but these are implemented in the table plugin. The issue arises as the incorrect name of the plugin "table" is passed as the first argument.
Overrode the function and corrected the name argument to be the correct one, "extended_table".
When selecting/deselecting the checkbox "Hide row numbers", the yasr result table is updated too …

Fixes yasr issues

---

ontotext-yasgui-web-component/src/components/confirmation-dialog/confirmation-dialog.scss

When attempting to delete a saved query with a long name, the name goes off the confirmation screen
The issue occurs when the saved query name is too long and cannot be broken into a new line.
Set the property `overflow-x: auto` on the dialog body.

GDB-9433: When trying to delete a saved query with a long name, the name goes off the confirmation screen

---

ontotext-yasgui-web-component/src/plugins/yasr/pivot-table/pivot-table-plugin.ts

There is a warning message when opening the "Google Chart" plugin. Scenario to Be Reproduced:
- Refresh the page (any page will do, just not the SPARQL view with the "Google plugin" open).
- Open the SPARQL view and execute a query if one is not already running.
- Click on the "Pivot Table" plugin.
- Click on the "Google Chart" plugin. The warning message "Attempting to load version 'current' of Google Charts, but the previously loaded version '1' will be used instead" should appear.
Changes have been made to how the [Google Chart library](https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code) is loaded. Both plugins use different methods for loading, leading to the appearance of the warning message.
Changed the "Table Plugin" to use the new …

GDB-9315: Warning Message in the Console After Clicking on Google Tab

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts

What
When hovering the mouse over a result cell with small width, the 'Copy Link' button was being displayed outside the cell.
Why
The button was hidden, when the table was displayed, its width was not considered in the cell width calculation.
How
A flex style is applied to the parent of the table cell elements to properly center the positioning of elements. Additionally, a span element is added after the 'Copy Link' button. The span is set with a min-width corresponding to the width of the 'Copy Link' button. When the mouse hovers over the cell, the 'Copy Link' button becomes visible, and the span invisible.

Fixed the position of the 'Copy Link' button when a cell is collapsed.

---

Yasgui/packages/yasr/src/plugins/table/index.scss
Yasgui/packages/yasr/src/plugins/table/index.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
yasgui-patches/2024-02-02-GDB-9476__Some_queries_with_empty_results_squish_the_cells.patch

This issue arises when there are no triples matching the query, leading to improper display empty row message.
The empty result message is displayed as row of datatable (jquery datatable behaviour). But the first column (row number) can be hidden and this causes the issues.
Added properly colSpan property of td tab where the message is displayed.
Added translation of empty result label.
The "Filter search results" input and both "Compact view" and "Hide row numbers" checkboxes are disabled when there are no results.

GDB-9476: Some queries with empty results squish the cells

---

Yasgui/packages/yasr/src/plugins/table/extended-table.ts
ontotext-yasgui-web-component/src/i18n/locale-fr.json

Fix query explain plan styling when displayed in multiple yasgui tabs.
There was a wrong selector from the document for the explain plan html element on which the styling should be applied which in this case was always the first yasgui tab where there is one. In result the rest tabs with displayed explain plan remained unstyled.
* Fixed selector for the explain plan element to be relative to current yasr.
* Also fixed a label for the abort query button.

GDB-9483 fix query explain plan styling when displayed in multiple yasgui tabs

---

cypress/e2e/yasr/sparql-result-formatting.spec.cy.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss

Improve styling of yasr results containing long strings.
Appears we broke styling of results in the table cells when we applied the flexbox in order to properly show the copy uri button. This made the `overflow-wrap:break-word` ineffective because our cells had fixed width in the table and in result any long string which didn't fit overflowed the cell.
* Replaced the `overflow-wrap: break-word` with `overflow-wrap: anywhere`. See a good explanation why here https://dev.to/somshekhar/overflow-wrap-in-a-flex-container-35
* Also improved styling of the rdf star triples which were also broken by the flex container.

GDB-8247 improve styling of yasr results containing long strings

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss

Fix explain plan styling
It was affected by incorrect css selector which used to apply flexbox on each div inside the results table cells.
Fixed by narrowing the selector to match only the immediate div child inside the table cells and not the entire possible div tag hierarchy in the cell.

GDB-9500 fix explain plan styling

---

ontotext-yasgui-web-component/src/components/ontotext-editable-text-field/ontotext-editable-text-field.component.tsx

When open a tab for renaming the input field is on focus but not selected.
Whe the name is selected the user can start typing the new name instead to delete the old name.
Made the input selected when rename form is opened.

GDB-9480: when open rename form the tab name should be selected

---

Yasgui/packages/yasr/src/plugins/table/extended-table.ts
Yasgui/packages/yasr/src/plugins/table/index.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
yasgui-patches/2024-02-09-GDB-9242__Refactoring_the_compact_view_functionality.patch

When selecting/deselecting the checkbox "Compact view", the yasr result table is updated too slowly.
The ellipse functionality is created during the table initialization. The table behaves differently depending on the value of the checkbox, causing the entire table to be re-rendered when the checkbox value is changed.
- When the "Compact view" is switched on: Two major changes occur; a class "ellipseTable" is added to the table element. The cells' contents are ellipsed, and when a user clicks on an ellipsed cell, the ellipsis is turned off for that cell, allowing the user to see the full content of the cell. If the content is a link, clicking on it twice will open the link. The table creation involves calculating the width for each cell to determine if the content will overflow, and if it …

GDB-9242: Refactoring the compact view functionality

---

Yasgui/packages/utils/src/index.ts
Yasgui/packages/yasqe/src/index.ts
yasgui-patches/2024-02-12-GDB-9479_Different_French_label_on_button_Abort_query.patch

- The "Abort query" label and tooltip are not translated when the language is changed.
The labels are translated during button initialization and when the button is clicked. However, the update of labels when the language is changed was not implemented.
The translation service has a new functionality that notifies registered observers when the language changes. An observer registration for the language change event has been added, and labels are updated when the event occurs.

GDB-9479: Different French label on button Abort query

---

Yasgui/packages/yasgui/src/Tab.ts
cypress/e2e/yasgui-tabs.spec.cy.ts
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/js/ontotext-yasgui-tests-util.js
ontotext-yasgui-web-component/src/pages/actions/main.js
ontotext-yasgui-web-component/src/pages/default-view/main.js
ontotext-yasgui-web-component/src/pages/multicolumn-results/main.js
ontotext-yasgui-web-component/src/pages/pagination/main.js
ontotext-yasgui-web-component/src/pages/yasr-plugins/main.js
yasgui-patches/2024-02-12-GDB-9514_prevent_closing_last_yasgui_tab.patch

Prevent closing last yasgui tab and show notification message.
For consistency with the old yasgui.
Check for existing tabs count and trigger a notification via the generic output emitter.

GDB-9514 prevent closing last yasgui tab

---

cypress/steps/yasr-steps.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts

When the column containing an RDF star link is too small, the 'Copy link' button is not properly displayed.
The rdf star link styling is not properly set.
Modified the HTML of RDF star links and applied proper styling.
- Added a 'Copy Link' button to 'open an RDF star' link when the link is hovered;
- Added a tooltip (title) with the value of the hovered link to the 'Copy Link' button because when the column is small, the link is broken into many lines or is ellipsised, making it hard to understand which link will be copied.

GDB-9528: Copy link buttons for an RDF star link are not properly displayed.

---

ontotext-yasgui-web-component/src/components/ontotext-editable-text-field/ontotext-editable-text-field.component.tsx

When open a tab for renaming the input field is on focus but not selected.
When the name is selected the user can start typing the new name instead to delete the old name.
Made the input selected when rename form is opened.

Cherry-pick from main GDB-9480: when open rename form the tab name should be selected

---

Yasgui/packages/yasgui/src/Tab.ts
cypress/e2e/yasgui-tabs.spec.cy.ts
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/js/ontotext-yasgui-tests-util.js
ontotext-yasgui-web-component/src/pages/actions/main.js
ontotext-yasgui-web-component/src/pages/default-view/main.js
ontotext-yasgui-web-component/src/pages/multicolumn-results/main.js
ontotext-yasgui-web-component/src/pages/pagination/main.js
ontotext-yasgui-web-component/src/pages/yasr-plugins/main.js
yasgui-patches/2024-02-12-GDB-9514_prevent_closing_last_yasgui_tab.patch

Prevent closing last yasgui tab and show notification message.
For consistency with the old yasgui.
Check for existing tabs count and trigger a notification via the generic output emitter.

Cherry pick from main GDB-9514 prevent closing last yasgui tab

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/services/utils/visualisation-utils.ts

Properly switch yasgui modes when tabs are switched or opened.
* When switching to editor only mode, then changing to another tab or opening a new tab won't preserve the selected mode.
* When switching to horizontal layout (2-columns), then yasqe spans the entire available page height, but when opening new tab or switching to another opened one, then yasqe shrinks to its default height.
* Added handlers for the tabAdd and tabSelect events where the mode is reapplied.
* Fixed the setYasqeFullHeight function to select properly the currently opened editor. Previous implementation used to select the first editor available in the DOM whereas its possible to have multiple tabs and editors respectively in the DOM.
* Also fixed a bug where switching to horizontal layout and then switching to …

GDB-9628 properly switch yasgui modes when tabs are switched or opened

---

Yasgui/packages/yasqe/src/index.ts

Turn off double click or YASQE resizer.
We don't want this behavior, when the component is used with other components in a view, this behavior can make the view look strange.
The functionality has been removed.

GDB-9318: Scrollbar in Sparql editor (Yasqe)

---

ontotext-yasgui-web-component/README.md
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts

Introduce a new configuration option, "showYasqeResizer."
This provides clients with the ability to toggle the visibility of the yasqe resizer.
The original yasgui has a "resizeable" configuration with a default value of true, controlling when the yasqe resizer is displayed. The newly exposed "showYasqeResizer" configuration allows clients to change this value as needed.

Expose a new "showYasqeResizer" configuration.

---

yasgui-patches/2024-02-26-GDB-9318__Scrollbar_in_Sparql_editor.patch

There are missed "2024-02-26-GDB-9318__Scrollbar_in_Sparql_editor_(Yasqe)" patch.
It was missed when the "GDB-9318-Scrollbar_in_Sparql_editor_(Yasqe)" issue was fixed.
The missed patch has been added.

Added "2024-02-26-GDB-9318-Scrollbar_in_Sparql_editor_(Yasqe)" patch.

---

ontotext-yasgui-web-component/README.md
ontotext-yasgui-web-component/src/models/external-yasgui-configuration.ts
ontotext-yasgui-web-component/src/models/yasgui-configuration.ts
ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts

Introduce a new configuration option, "showYasqeResizer".
This provides clients with the ability to toggle the visibility of the yasqe resizer.
The original yasgui has a "resizeable" configuration with a default value of true, controlling when the yasqe resizer is displayed. The newly exposed "showYasqeResizer" configuration allows clients to change this value as needed.

Cherry-pick from 1.2 Expose a new "showYasqeResizer" configuration.

---

Yasgui/packages/yasgui/src/Tab.ts
Yasgui/packages/yasqe/src/index.ts
ontotext-yasgui-web-component/src/services/translation.service.ts
yasgui-patches/2024-02-28-fixes_issues_with_resources.patch

GDB-9678: The 'Abort' button doesn't get translated when there are multiple running queries.
If there are more than one "Abort query" button, only the first one is translated when the language is changed.
TranslationService has subscription functionality, which gives opportunity to attach function that will be called when the language is changed. Every one event observer is registered with event name. Registration is one name to one notification function. The registration of the 'Abort query' button occurs when a Yasqe instance is created, and it is associated with a single name. This is the reason only one button is notified when the event occurs.
Changed subscription functionality to support many callback functions for one name.
All listeners of YASQE are not released when the tab is …

Gdb 9678 the abort button doesn't get translated when there are multiple running queries

---

cypress/e2e-flaky/yasr/plugins/table/copy-link-dialog.spec.cy.ts
cypress/e2e/rdf-star.spec.cy.ts
cypress/steps/pages/rdf-star-page-steps.ts
cypress/steps/yasr-steps.ts
ontotext-yasgui-web-component/src/pages/fake-server.js
ontotext-yasgui-web-component/src/pages/rdf-star/index.html
ontotext-yasgui-web-component/src/pages/rdf-star/main.js
ontotext-yasgui-web-component/src/pages/yasr-plugins/main.js
ontotext-yasgui-web-component/src/services/utils/html-util.ts
ontotext-yasgui-web-component/src/services/yasr/yasr-service.ts

Fix escaping triples when copy link dialog is triggered.
In the utility function which was used to escape the uri was missed the possibility to have a literal in the triple which used to cut literals during the escaping.
Fixed the escape function to properly escape the double quotes around string literals. Also added test.

GDB-9578 fix triple escaping when copying link

---

Yasgui/packages/yasr/src/plugins/error/extended-error.ts

Add alert class to error plugin element.
Basically this element needs to be styled as an alert component with error type color and it has the color but when the dark theme gets applied, then alert element color is inverted using css filter and as far as this element currently doesn't have the `alert` class it remains unaffected by the filter.
Just added the alert class to the root element.

GDB-9409 add alert class to error plugin element

---

Yasgui/packages/yasgui/src/Tab.ts
Yasgui/packages/yasqe/src/index.ts
ontotext-yasgui-web-component/src/services/translation.service.ts
yasgui-patches/2024-02-29-fixes_issues_with_resources.patch

If there are more than one "Abort query" button, only the first one is translated when the language is changed.
TranslationService has subscription functionality, which gives opportunity to attach function that will be called when the language is changed. Every one event observer is registered with event name. Registration is one name to one notification function. The registration of the 'Abort query' button occurs when a Yasqe instance is created, and it is associated with a single name. This is the reason only one button is notified when the event occurs.
Changed subscription functionality to support many callback functions for one name.

Cherry pick from 1.2 GDB-9678: The Abort button doesn't get translated when there are multiple running queries

---

Yasgui/packages/yasqe/src/index.ts
yasgui-patches/2024-03-01-01-skip_aborting_the_query_if_the__onQueryAborted__function_is_passed_to_the_configuration.patch

What
Skip aborting the query if the "onQueryAborted" function is passed to the configuration.
Why
If client want to control aborting of ongoing query, it can pass function "onQueryAborted".
How
Added check if function is passed then the ongoing query is not aborted, this will be responsibility of the client.

Skip aborting the query if a function is passed to the configuration

---

Yasgui/packages/yasqe/src/index.ts
yasgui-patches/2024-03-05-1-Skip_aborting_the_query_if_the__onQueryAborted__function_is_passed_to_the_configuration.patch

Skip aborting the query if the "onQueryAborted" function is passed to the configuration.
If client want to control aborting of ongoing query, it can pass function "onQueryAborted".
Added check if function is passed then the ongoing query is not aborted, this will be responsibility of the client.
cherry-pick from [commit 412cde7...](https://github.com/Ontotext-AD/ontotext-yasgui/commit/412cde77f8531ae42ffebc4e383328de3b15ff1b)

Cherry pick form 1.2.8 skip aborting the query if the on query aborted function is passed to the configuration

---

Yasgui/packages/yasr/src/index.ts
Yasgui/packages/yasr/src/plugins/table/extended-table.ts
cypress/steps/yasr-steps.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
yasgui-patches/2024-03-05-2-the_page_freezes_when_clicking_on_compact_view_or_hide_row_numbers.patch

When there are many results to be displayed, and either the 'Compact view' or 'Hide row numbers' checkbox is clicked, the browser becomes unresponsive. The page freezes, and the user cannot discern what has happened.
Clicking either checkbox adds a class to the result table, triggering the browser to apply new styles. This operation can be slow, especially with many cells in the table.
A loader has been added to notify users that the browser is re-rendering the result, indicating that they need to wait.

GDB-9719 The page freezes when clicking on 'Compact view' or 'Hide row numbers

---

ontotext-yasgui-web-component/src/components/alert-box/alert-box.scss
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx

The layout orientation has been changed to horizontal.
To improve the usage of the component. The old implementation had some issues with component height calculations when used on certain pages.
The problem arose due to the parent-child relations of the original implementation, which did not account for horizontal alignment of YASQE, YASR, and the tab list. We attempted to address this using flexbox, but encountered unexpected issues with the component's clients.
The flexbox implementation has been removed. Now, the width of YASQE, YASGUI, and the tab list is set to 50% when YASGUI mode is horizontal.
Added a listener that observes changes in the tabs list size. When the event occurs, the position of the YASR is recalculated to align it with the top of the tabs list component.

Changes horizontal orientation layout.

---

Yasgui/packages/yasr/src/plugins/table/extended-table.ts
cypress/e2e/yasr/plugins/table/compact-view.spec.cy.ts
cypress/fixtures/queries/many-column-response.json
cypress/steps/pages/compact-view-page-steps.ts
cypress/steps/yasr-table-plugin-steps.ts
cypress/stubs/query-stubs.ts
cypress/support/commands.js
cypress/support/index.d.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/index.html
ontotext-yasgui-web-component/src/pages/compact-view/index.html
ontotext-yasgui-web-component/src/pages/compact-view/main.js
ontotext-yasgui-web-component/src/pages/fake-server.js
yasgui-patches/2024-03-15-GDB-9946_Workbench_should_allow_to_copy_any_long_truncated_value.patch

When the result table is truncated with ellipses, the literal values of the cells cannot be selected and copied by the user.
This issue arises particularly when the result table is in 'Compact view,' where all cell values are truncated with ellipses and cannot be selected for copying.
Implemented functionality that gives the opportunity to the client to view the full content of a truncated cell with ellipsis when they click on it.
Added three listeners:
- "mouseover" - the handler add "expandable-literal" class if string literal is truncated with ellipses. Adding the "expandable-literal" class will change cursor to point when literal is hovered;
- "mouseout" - the handler will remove the "expandable-literal";
- "click" - the handler add "expanded-literal" class. Adding the …

GDB-9946: Workbench should allow to copy any long (truncated) value

---

Yasgui/packages/yasgui/src/Tab.ts
Yasgui/packages/yasqe/src/index.ts
Yasgui/packages/yasr/src/index.ts
yasgui-patches/2024-03-22-1-GDB-9964_Clear_data_for_old_ran_query_after_new_query_is_executed.patch

The browser freezes when switching between tabs. To reproduce this scenario:
- Opens at least two tabs;
- Execute a query that returns many results (many columns and rows). For example:
```
select * where {
?s ?p ?o . 
?s1 ?p1 ?o1 . 
?s1 ?p2 ?o2 . 
?s1 ?p3 ?o3 . 
?s1 ?p4 ?o4 . 
?s1 ?p5 ?o5 . 
?s1 ?p6 ?o6 . 
?s1 ?p7 ?o7 . 
?s1 ?p8 ?o8 . 
?s1 ?p9 ?o9 . 
.... 
}
```
- Wait until the results are displayed;
- Execute a long-running query, for instance
```
select (count(*) as ?count) where {
?s ?p ?o.
?s1 ?p1 ?o1.
?s2 ?p2 ?o2.
?s3 ?p3 ?o3.
}
```
At this point, toggling between tabs is slow, especially when switching to the tab that had many results. It should load quickly because a new query is executed and there are no results to be displayed.
When a new query is run, the results from the …

GDB-9964: Clear data for old ran query after new query is executed

---

cypress/e2e/languages.spec.cy.ts
cypress/steps/languages-steps.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/pages/languages/main.js

When the component is initialized with a language different from the default "en," the change mode buttons still display in English.
This is an old bug that originated when we introduced the language field to the configuration. Here's how the functionality works:
- The component is created and translated based on the configuration language.
- Initially, the component's language property is set to the default "en," resulting in English labels for the buttons during initialization.
- Later, when the componentDidLoad hook is called, the client configuration updates the language to, for example, French.
- Although inner components are re-rendered with the new translations, the main component's buttons remain untranslated because its state is not changed, and it's not re-rendered.
Refactored …

Fixes translation issue with buttons that change the component modes "Yasqe," "Yasgui," or "Yasr.

---

Yasgui/packages/yasr/src/plugins/table/extended-table.ts
cypress/e2e/yasr/plugins/table/sort-results.spec.cy.ts
cypress/steps/pages/yasr-table-sorting-page.steps.ts
cypress/steps/yasr-steps.ts
ontotext-yasgui-web-component/src/pages/fake-server.js
ontotext-yasgui-web-component/src/pages/yasr-table-sorting/index.html
ontotext-yasgui-web-component/src/pages/yasr-table-sorting/main.js
yasgui-patches/2024-05-16-GDB-3107-allow-sorting-of-results-table-by-column-type.patch

Extend datatable to allow sorting individual columns based on the values type.
Currently the table allows sorting only by string, but sparql results can come with different datatypes for each binding. It'd be convenient to properly sort the table based on the type of the data in the respective column being sorted on.
Implemented custom ordering functions for numbers, dates and strings which also remains the default if no datatype is found. The table settings is augmented with additional columnDef property providing the types for each column so that ordering functions to be able to properly order results. Also the column render function was extended with logic which converts the cell value to proper type based on the datatype from the results binding.

GDB-3107 extend datatable to allow sorting individual columns based on the values type

---

ontotext-yasgui-web-component/src/components/ontotext-tooltip-web-component/ontotext-tooltip-web-component.scss
ontotext-yasgui-web-component/src/components/ontotext-tooltip-web-component/ontotext-tooltip-web-component.tsx
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss

- The tooltips in Google editor are not visible.
- There are double tooltips when hovering over a SPARQL editor button. How to reproduce:
- Open SPARQL view;
- Execute a query (the query type doesn't matter); -Switch to “Pivot Table” and choose a Google renderer (e.g., Bar chart) or simply switch to the “Google Chart” plugin; - Click on the “Chart config” button; - When the “Chart editor” dialog opens, hover the mouse over some recommended charts (at this point, a div with the class “jfk-tooltip” is appended to the DOM; this is the reason for the issue); - Hover the mouse over some SPARQL editor buttons.
- The tooltip is under the chart editor dialog;
- The chart editor tooltip is implemented as a div element with the "jfk-tooltip" class. When the mouse hovers over a chart editor element, …

GDB-10292: Doubled hover on menus in SPARQL section.

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss

What
The Google tooltip blinks when the mouse is over Google Pie charts.
Why
- Mousing over the chart activates the popup;
- The popup is superimposed on top of the chart and under the pointer. This situation activates the flicker;
- The pointer is no longer over the chart (because it's over the popup), and therefore the popup is removed;
- This creates a loop (Go to 1).
The reason is described at https://github.com/google/google-visualization-issues/issues/2162.
How
Removes pointer events from Google tooltips as suggested in https://github.com/google/google-visualization-issues/issues/2162".

GDB-10304: Blinking hovers on Google Pie charts

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss

When the horizontal scroll appears in the YASR results, the user will be able to scroll and still see the row numbers column.
The column with row numbers was not frozen before and it was easy to forget which row you are on, while scrolling.
I added styling to freeze the column and match the row background color.

GDB-9448 - Freeze row numbers in the YASR results

---

ontotext-yasgui-web-component/src/models/ontotext-yasgui.ts
ontotext-yasgui-web-component/src/models/yasgui/yasqe.ts

When pasting a value in the editor, the editor will not scroll the cursor to the bottom.
Previously, the editor would scroll the cursor line to the bottom of the CodeMirror input, regardless how many lines were pasted.
**The cause**: when we set the prefixes for a query in the Workbench and pass it along to the YASGUI, the method which sets the value in the editor, triggers the CodeMirror to scroll its content to the cursor position. 
Alternative function for setting the query is used, instead of the one causing the scroll issue. The cursor position is preserved.

GDB-9968 - Prevent CodeMirror auto-scroll on paste

---

ontotext-yasgui-web-component/src/services/utils/html-util.ts

HTML entity "&" in literals will not be encoded when shown in the results.
The "&" will be escaped as "&amp;" to prevent XSS vulnerabilities.
I extended the encoding method.
For example, if the data is entered as "Real power in watts (J/s). Electrical power may have real and reactive components. The real portion of electrical power (I&#178;R or VIcos(phi)), is expressed in Watts. See also apparent power and reactive power.", the fetched result will be the one in the second row in the screenshot.

GDB-10876 - Add escape HTML entity "&"

---

cypress/e2e/saved-query/delete-saved-query.spec.cy.ts
cypress/e2e/saved-query/edit-saved-query.spec.cy.ts
cypress/e2e/saved-query/share-saved-query.spec.cy.ts
cypress/steps/yasqe-steps.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/saved-queries-popup/saved-queries-popup.tsx
ontotext-yasgui-web-component/src/models/saved-query-configuration.ts
ontotext-yasgui-web-component/src/pages/actions/main.js

The saved query model has been extended with an additional property, "readonly".
When the property is set to true, the edit and delete buttons are hidden.
- The SavedQuery model has been extended with a new property, "readonly";
- saved-queries-popup.tsx has been updated to hide the edit and delete buttons if the query is marked as readonly.
read-only

GDB-11281: Extend Saved Query Functionality

---

ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json

The "Download as" button label in the **Table** tab has been changed to "Download as SPARQL Results JSON".
The file format for JSON option was `.srj`, which confused some users. This new label was approved as more descriptive.
I edited the text.

GDB-10933 - add more descriptive label to "Download as" button

---

cypress/e2e/editor-actions/save-query.spec.cy.ts
cypress/e2e/saved-query/edit-saved-query.spec.cy.ts
cypress/stubs/constants.ts
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx
ontotext-yasgui-web-component/src/components/save-query-dialog/save-query-dialog.tsx
ontotext-yasgui-web-component/src/components/saved-queries-popup/saved-queries-popup.tsx
ontotext-yasgui-web-component/src/i18n/locale-en.json
ontotext-yasgui-web-component/src/i18n/locale-fr.json
ontotext-yasgui-web-component/src/models/saved-query-configuration.ts

The original name of the query will be added to the event data on saved query edit.
The original name is required by GDB to allow editing the name of a saved query.
I added the new field to the query objects.

GDB-12134 - Add an original name property to the Query Data

---

ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.tsx

Fix component not reinitializing if unmounted and then mounted again
The component was initialized in `componentDidLoad` which runs only once. If the component was later unmounded, the `disconnectedCallback` would destroy the YASGUI instance, but upon mounting the initialization would not run again.
- Added initialization routine in `connectedCallback`

GDB-12633: SPARQL Editor copied query templates URLs not working

---

ontotext-yasgui-web-component/README.md
ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
ontotext-yasgui-web-component/src/components/save-query-dialog/save-query-dialog.scss
ontotext-yasgui-web-component/src/css/_common.scss

In dark mode, the background color of text inputs and textareas appears white, causing readability issues.
The background colors for text inputs and textareas were not explicitly defined, leaving them to depend on the browser’s default styling, which may conflict with dark themes.
Explicitly set the background color for text inputs and textareas to ensure consistent visibility across all themes, including dark mode.
Also fixes background issues in rename and create saved query dialog inputs and textareas.
| Before | After | 
|----------|----------|
| <img width="320" alt="image" src="https://github.com/user-attachments/assets/1aaa9284-85e7-43ea-8c31-6f227388a57c" />   | <img width="320" alt="image" src="https://github.com/user-attachments/assets/eedbc6fe-0016-41ac-998d-36566cfe7e6a" />  | …

GDB-13149: Copy URL is White on White Background
